import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Toaster } from "@/components/ui/toaster";
import { cookies } from "next/headers";
import { createClient } from "@/lib/supabase/server";
import CustomProvider from "../providers/CustomProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "HIYORI | Ecommerce Platforum Built with Nextjs 14.",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cookieStore = cookies();
  const supabase = createClient({ cookieStore });
  const {
    data: { user },
  } = await supabase.auth.getUser();
  const {
    data: { session },
  } = await supabase.auth.getSession();

  return (
    <html lang="en">
      <body className={inter.className}>
        <CustomProvider initialUser={user} initialSession={session}>
          {children}
          <Toaster />
        </CustomProvider>
      </body>
    </html>
  );
}
